# Hands-on DS: NumPy Array Exercises

Hands-on Exercises for Lec. 13 of UFUG1601-ICS at HKUST-GZ\
Created by Guoming Tang\
Latest update: Oct. 29, 2024

## 1. Creating NumPy Arrays

In [2]:
import numpy as np

# Creating different types of arrays
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 3))
eye_array = np.eye(3)
arange_array = np.arange(10)
random_array = np.random.random((3, 3))
random_int_array = np.random.randint(1, 100, size=(10,10))

print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)
print("Eye Array:\n", eye_array)
print("Arange Array:\n", arange_array)
print("Random Array:\n", random_array)
print("Random Integer Array:\n", random_int_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Eye Array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange Array:
 [0 1 2 3 4 5 6 7 8 9]
Random Array:
 [[0.60118421 0.82113978 0.21888469]
 [0.78337191 0.40993146 0.36348588]
 [0.03400175 0.17754121 0.90647124]]
Random Integer Array:
 [[85 70 14 59 59 83 46 14 11 22]
 [32 19 98 67 80 72 33 70 23 21]
 [84 30 80 67  3 15 98 59 53 74]
 [37 27  3 44 16 82 28 85 43 81]
 [12 90 37 69 29 81 16 46 32 81]
 [63  1 16 66 78 58 93 40 85 38]
 [75 45 56 10 88 25 85 27 68 64]
 [43 80 54 97 62 51 36 98 54 14]
 [ 3 48 90 39 75 66 74 44 10 50]
 [83 90 35 66 50 76 21 37 78 69]]


**Exercise 1:**
- Create a 2D array with shape `(4, 4)` filled with zeros.
- Generate an array with numbers from 20 to 40. (Hint: using _arange(min, max)_)


In [1]:
arr1=np.zeros((4,4))
arr2=np.arange(20,41)
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

NameError: name 'np' is not defined

## 2. Basic NumPy Array Operations


In [5]:
# Array attributes
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)

# Indexing and slicing
print("Element at (0,1):", array[0, 1])
print("First row:", array[0, :])
print("Last column:", array[:, -1])


Shape: (3, 3)
Size: 9
Data type: int32
Element at (0,1): 2
First row: [1 2 3]
Last column: [3 6 9]


**Exercise 2:**
- Create a 3x3 array of random integers between 10 and 50.
- Slice out the first two columns from this array.


In [7]:
random_array = np.random.randint(10,51,size=(3,3))
print("Random Array:\n", random_array)
print("two columns:\n", random_array[:,:2])


Random Array:
 [[11 31 24]
 [31 17 16]
 [30 22 19]]
two columns:
 [[11 31]
 [31 17]
 [30 22]]


## 3. NumPy Array Concatenation and Splitting


In [8]:
# Reshaping arrays
array = np.arange(1, 10)
reshaped_array = array.reshape(3, 3)
print("Original array:", array)
print("Reshaped array:\n", reshaped_array)

# Concatenation and splitting
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate([array1, array2])
print("Concatenated array:", concatenated_array)

split_array = np.split(concatenated_array, [3])
print("Split array:", split_array)


Original array: [1 2 3 4 5 6 7 8 9]
Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Concatenated array: [1 2 3 4 5 6]
Split array: [array([1, 2, 3]), array([4, 5, 6])]


**Exercise 3:**
- Create a 1D array from 0 to 15 and reshape it into a 4x4 matrix.
- Concatenate two arrays of size 4 and split the result into three parts.


In [12]:
array=np.arange(0,16)
resh_arr=array.reshape(4,4)
print("Original Array:\n", array)
print("Reshaped Array:\n", resh_arr)

array1 = np.array([1, 2, 3,666])
array2 = np.array([4, 5, 6,888])
conca_arr=np.concatenate([array1,array2])
split_arr = np.array_split(conca_arr, 3)
print("Concatenated Array:\n", conca_arr)
print("Split Array:\n", split_arr)



Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Concatenated Array:
 [  1   2   3 666   4   5   6 888]
Split Array:
 [array([1, 2, 3]), array([666,   4,   5]), array([  6, 888])]


## 4. Computation on NumPy Arrays


In [13]:
# Universal functions
array = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Square root:", np.sqrt(array))

# Broadcasting
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
broadcasted_sum = a + b
print("Broadcasted sum:\n", broadcasted_sum)


Sum: 15
Mean: 3.0
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Broadcasted sum:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


**Exercise 4:**
- Creat a 2D array and compute the product of all elements in the array.
- Creat a 1D array and perform broadcasting to add the 1D array to each row of the above 2D array.


In [20]:
#your codes
ori_arr=np.random.randint(1,10,size=(3,3))
print("Original array:", ori_arr)
print("compute the product all the elements of the array:", np.prod(ori_arr))
add_arr=np.random.randint(1,20,size=(3))
print("Array to add:", add_arr)
for arr in ori_arr:
    arr+=add_arr
print("after adding the elements of the array:", ori_arr)

Original array: [[6 5 7]
 [3 5 2]
 [2 6 8]]
compute the product all the elements of the array: 604800
Array to add: [ 8 15  4]
privious array: [[14 20 11]
 [11 20  6]
 [10 21 12]]
after adding the elements of the array: [[14 20 11]
 [11 20  6]
 [10 21 12]]


## 5. Sorting, Comparisons, and Boolean Logic


In [21]:
# Sorting
array = np.array([4, 2, 7, 1, 3])
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# Comparisons and masks
boolean_mask = array > 3
print("Elements greater than 3:", array[boolean_mask])


Sorted array: [1 2 3 4 7]
Elements greater than 3: [4 7]


**Exercise 5:**
- Sort an array of random integers between 10 and 50.
- Find all elements in a NumPy array that are less than a given threshold.


In [3]:
#your codes
array=np.random.randint(10,51,size=(3,3))
array.sort()
print("Sorted Array:\n", array)
threshold=30
boolean_mask=array<threshold
print("Elements less than threshold:", array[boolean_mask])

Sorted Array:
 [[11 20 26]
 [28 43 44]
 [23 34 36]]
Elements less than threshold: [11 20 26 28 23]


In [7]:
arr_1d=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
sum_arr=arr_1d+arr_2d
print("Sum of two arrays:\n", sum_arr)
mult_arr=arr_1d*arr_2d
print("Product of two arrays:\n", mult_arr)
subt_arr=arr_2d-arr_1d
print("Difference of two arrays:\n", subt_arr)

mean_2d=np.mean(arr_2d)
median_2d=np.median(arr_2d)
sta_dev_2d=np.std(arr_2d)
print("Mean of 2D array:", mean_2d)
print("Median of 2D array:", median_2d)
print("Standard Deviation of 2D array:", sta_dev_2d)

arr_2d_1=np.array([[2,2,2],[5,5,5],[8,8,8]])
matrix_arr=np.dot(arr_2d,arr_2d_1)
print("Matrix 1:\n", arr_2d)
print("Matrix 2:\n", arr_2d_1)
print("Matrix Multiplication:\n", matrix_arr)
det_2d=np.linalg.det(arr_2d_1)
print("Determinant of 2D array:", det_2d)


Sum of two arrays:
 [[2 4 6]
 [5 7 9]]
Product of two arrays:
 [[ 1  4  9]
 [ 4 10 18]]
Difference of two arrays:
 [[0 0 0]
 [3 3 3]]
Mean of 2D array: 3.5
Median of 2D array: 3.5
Standard Deviation of 2D array: 1.707825127659933
Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[2 2 2]
 [5 5 5]
 [8 8 8]]
Matrix Multiplication:
 [[36 36 36]
 [81 81 81]]
Determinant of 2D array: 0.0


In [14]:
new_arr=np.random.randint(1,10,size=(3,3))
slice_arr=new_arr[1:3,0:2]
index_get=new_arr[1,1]
print("Original Array:\n", new_arr)
print("Sliced Array:\n", slice_arr)
print("Index Element:", index_get)

arr_1dto2d=arr_1d.reshape(3,1)
arr_2dto1d=new_arr.flatten()
print("1D to 2D:\n", arr_1dto2d)
print("2D to 1D:\n", arr_2dto1d)

arr_1d_1=np.array([1,2,3])
arr_broadcast=arr_1d_1+arr_1dto2d
print("Broadcasted Array:\n", arr_broadcast)

compare_arr=new_arr[new_arr>3]
print("Elements greater than 3:\n", compare_arr)
new_arr_1=np.random.randint(1,10,size=(3,3))
compare_arr_1=new_arr>new_arr_1
print("Comparison Array:\n", new_arr[compare_arr_1])


Original Array:
 [[3 9 6]
 [3 5 7]
 [1 3 6]]
Sliced Array:
 [[3 5]
 [1 3]]
Index Element: 5
1D to 2D:
 [[1]
 [2]
 [3]]
2D to 1D:
 [3 9 6 3 5 7 1 3 6]
Broadcasted Array:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]
Elements greater than 3:
 [9 6 5 7 6]
Comparison Array:
 [9 3]


In [8]:
tenser_rad=np.random.randint(1,10,size=(3,3,3))
print("random Array:\n", tenser_rad)
tenser_spec=np.array([[[1,1,1],[2,2,2],[3,3,3]],[[4,4,4],[5,5,5],[6,6,6]],[[7,7,7],[8,8,8],[9,9,9]]])
tenser_add=tenser_rad+tenser_spec
tenser_sub=tenser_rad-tenser_spec
tenser_mul=tenser_rad*tenser_spec
print("addition:\n", tenser_add)
print("subtraction:\n", tenser_sub)
print("multiplication:\n", tenser_mul)

dot_product=np.dot(tenser_rad[1,:2,:2],tenser_spec[1,:2,:2])
print("Dot Product:\n", dot_product)
slice_arr=tenser_rad[1,:2,:2]
print("Sliced arr:\n", slice_arr)

replace_arr=np.random.randint(1,10,size=(2,2,2))
tenser_rad[:2,:2,:2]=replace_arr
print("Replaced Array:\n", tenser_rad)

sum_col=np.sum(tenser_rad,axis=0)
mean_row=np.mean(tenser_rad,axis=1)
std_wid=np.std(tenser_rad,axis=2)
print("Sum of columns:\n", sum_col)
print("Mean of rows:\n", mean_row)
print("Standard Deviation of width:\n", std_wid)

random Array:
 [[[3 7 3]
  [9 2 9]
  [9 1 1]]

 [[2 7 3]
  [5 7 5]
  [6 3 3]]

 [[1 7 7]
  [6 6 7]
  [6 9 4]]]
addition:
 [[[ 4  8  4]
  [11  4 11]
  [12  4  4]]

 [[ 6 11  7]
  [10 12 10]
  [12  9  9]]

 [[ 8 14 14]
  [14 14 15]
  [15 18 13]]]
subtraction:
 [[[ 2  6  2]
  [ 7  0  7]
  [ 6 -2 -2]]

 [[-2  3 -1]
  [ 0  2  0]
  [ 0 -3 -3]]

 [[-6  0  0]
  [-2 -2 -1]
  [-3  0 -5]]]
multiplication:
 [[[ 3  7  3]
  [18  4 18]
  [27  3  3]]

 [[ 8 28 12]
  [25 35 25]
  [36 18 18]]

 [[ 7 49 49]
  [48 48 56]
  [54 81 36]]]
Dot Product:
 [[43 43]
 [55 55]]
Sliced arr:
 [[2 7]
 [5 7]]
Replaced Array:
 [[[9 9 3]
  [9 8 9]
  [9 1 1]]

 [[8 9 3]
  [7 3 5]
  [6 3 3]]

 [[1 7 7]
  [6 6 7]
  [6 9 4]]]
Sum of columns:
 [[18 25 13]
 [22 17 21]
 [21 13  8]]
Mean of rows:
 [[9.         6.         4.33333333]
 [7.         5.         3.66666667]
 [4.33333333 7.33333333 6.        ]]
Standard Deviation of width:
 [[2.82842712 0.47140452 3.77123617]
 [2.62466929 1.63299316 1.41421356]
 [2.82842712 0.47140452 

In [25]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

url = 'https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv'
df = pd.read_csv(url)
df.fillna(0, inplace=True)

labelencoder = LabelEncoder()
df['Country/Region'] = labelencoder.fit_transform(df['Country/Region'])
num_cols = df.columns[4:]
scaler = MinMaxScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

df.drop_duplicates(inplace=True)
df.to_csv('covid19_new.csv', index=False)
print(df)

    Province/State  Country/Region        Lat        Long  1/22/20  1/23/20  \
0                0               0  33.939110   67.709953      0.0      0.0   
1                0               1  41.153300   20.168300      0.0      0.0   
2                0               2  28.033900    1.659600      0.0      0.0   
3                0               3  42.506300    1.521800      0.0      0.0   
4                0               4 -11.202700   17.873900      0.0      0.0   
..             ...             ...        ...         ...      ...      ...   
284              0             196  31.952200   35.233200      0.0      0.0   
285              0             197  39.904200  116.407400      0.0      0.0   
286              0             198  15.552727   48.516388      0.0      0.0   
287              0             199 -13.133897   27.849332      0.0      0.0   
288              0             200 -19.015438   29.154857      0.0      0.0   

     1/24/20  1/25/20  1/26/20  1/27/20  ...   2/28

In [21]:
df_1=pd.read_csv('netflix_titles.csv')
type_group=df_1.groupby('type').agg({'title':'count'}).reset_index()

pivot_table=df_1.pivot_table(index='country',columns='type',values='title',aggfunc='count',fill_value=0)
print("pivot table:\n", pivot_table)

filter_data=df_1[df_1['release_year']>2015]
filtered_sorted_df = filter_data.sort_values(by='release_year')
print("Filtered and Sorted Data:\n", filtered_sorted_df)

pivot table:
 type                                                Movie  TV Show
country                                                           
, France, Algeria                                       1        0
, South Korea                                           0        1
Argentina                                              38       18
Argentina, Brazil, France, Poland, Germany, Den...      1        0
Argentina, Chile                                        2        0
...                                                   ...      ...
Venezuela                                               1        0
Venezuela, Colombia                                     1        0
Vietnam                                                 7        0
West Germany                                            1        0
Zimbabwe                                                1        0

[748 rows x 2 columns]
Filtered and Sorted Data:
      show_id     type                                           

In [22]:
df_info=pd.DataFrame({
    'director': ['Director A', 'Director B', 'Director C'],
    'country': ['USA', 'UK', 'Canada']
})
df_base=pd.DataFrame({
    'director': ['Director A', 'Director B', 'Director C'],
    'movie': ['Movie A', 'Movie B', 'Movie C'],
    'time': ['2h', '3h', '1h']
})
df_merge=pd.merge(df_base,df_info,on='director')
print("Merged Data:\n", df_merge)

Merged Data:
      director    movie time country
0  Director A  Movie A   2h     USA
1  Director B  Movie B   3h      UK
2  Director C  Movie C   1h  Canada
