# Hands-on DS: NumPy Array Exercises

Hands-on Exercises for Lec. 13 of UFUG1601-ICS at HKUST-GZ\
Created by Guoming Tang\
Latest update: Oct. 29, 2024

## 1. Creating NumPy Arrays

In [1]:
import numpy as np

# Creating different types of arrays
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 3))
eye_array = np.eye(3)
arange_array = np.arange(10)
random_array = np.random.random((3, 3))
random_int_array = np.random.randint(1, 100, size=(10,10))

print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)
print("Eye Array:\n", eye_array)
print("Arange Array:\n", arange_array)
print("Random Array:\n", random_array)
print("Random Integer Array:\n", random_int_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Eye Array:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange Array:
 [0 1 2 3 4 5 6 7 8 9]
Random Array:
 [[0.56420239 0.88314381 0.2669879 ]
 [0.96746441 0.55853858 0.99008786]
 [0.01338308 0.02613542 0.56104899]]
Random Integer Array:
 [[21 46 37  7 19 64 95 37 39 13]
 [77 40 69  7 16 97 13 55 67 72]
 [34 62 34 98 65 17 61 54 23 25]
 [98 56 92 49 48  5 96 77 41 73]
 [33 51 26 49 90 81 32 66 89 24]
 [28 25 40 96  5 80 19  8 65 41]
 [54 42 80 32 10 67 98 80 58 61]
 [39 87 69 11 41 95 88 72 25 10]
 [29 36 75 21 86 76 82 18 63 55]
 [37 53 90 44  7  3 61 72 58 81]]


**Exercise 1:**
- Create a 2D array with shape `(4, 4)` filled with zeros.
- Generate an array with numbers from 20 to 40. (Hint: using _arange(min, max)_)


In [4]:
arr1=np.zeros((4,4))
arr2=np.arange(20,41)
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

Array 1:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array 2:
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


## 2. Basic NumPy Array Operations


In [5]:
# Array attributes
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Shape:", array.shape)
print("Size:", array.size)
print("Data type:", array.dtype)

# Indexing and slicing
print("Element at (0,1):", array[0, 1])
print("First row:", array[0, :])
print("Last column:", array[:, -1])


Shape: (3, 3)
Size: 9
Data type: int32
Element at (0,1): 2
First row: [1 2 3]
Last column: [3 6 9]


**Exercise 2:**
- Create a 3x3 array of random integers between 10 and 50.
- Slice out the first two columns from this array.


In [7]:
random_array = np.random.randint(10,51,size=(3,3))
print("Random Array:\n", random_array)
print("two columns:\n", random_array[:,:2])


Random Array:
 [[11 31 24]
 [31 17 16]
 [30 22 19]]
two columns:
 [[11 31]
 [31 17]
 [30 22]]


## 3. NumPy Array Concatenation and Splitting


In [8]:
# Reshaping arrays
array = np.arange(1, 10)
reshaped_array = array.reshape(3, 3)
print("Original array:", array)
print("Reshaped array:\n", reshaped_array)

# Concatenation and splitting
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
concatenated_array = np.concatenate([array1, array2])
print("Concatenated array:", concatenated_array)

split_array = np.split(concatenated_array, [3])
print("Split array:", split_array)


Original array: [1 2 3 4 5 6 7 8 9]
Reshaped array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Concatenated array: [1 2 3 4 5 6]
Split array: [array([1, 2, 3]), array([4, 5, 6])]


**Exercise 3:**
- Create a 1D array from 0 to 15 and reshape it into a 4x4 matrix.
- Concatenate two arrays of size 4 and split the result into three parts.


In [12]:
array=np.arange(0,16)
resh_arr=array.reshape(4,4)
print("Original Array:\n", array)
print("Reshaped Array:\n", resh_arr)

array1 = np.array([1, 2, 3,666])
array2 = np.array([4, 5, 6,888])
conca_arr=np.concatenate([array1,array2])
split_arr = np.array_split(conca_arr, 3)
print("Concatenated Array:\n", conca_arr)
print("Split Array:\n", split_arr)



Original Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Concatenated Array:
 [  1   2   3 666   4   5   6 888]
Split Array:
 [array([1, 2, 3]), array([666,   4,   5]), array([  6, 888])]


## 4. Computation on NumPy Arrays


In [13]:
# Universal functions
array = np.array([1, 2, 3, 4, 5])
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))
print("Square root:", np.sqrt(array))

# Broadcasting
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])
broadcasted_sum = a + b
print("Broadcasted sum:\n", broadcasted_sum)


Sum: 15
Mean: 3.0
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Broadcasted sum:
 [[11 12 13]
 [21 22 23]
 [31 32 33]]


**Exercise 4:**
- Creat a 2D array and compute the product of all elements in the array.
- Creat a 1D array and perform broadcasting to add the 1D array to each row of the above 2D array.


In [20]:
#your codes
ori_arr=np.random.randint(1,10,size=(3,3))
print("Original array:", ori_arr)
print("compute the product all the elements of the array:", np.prod(ori_arr))
add_arr=np.random.randint(1,20,size=(3))
print("Array to add:", add_arr)
for arr in ori_arr:
    arr+=add_arr
print("after adding the elements of the array:", ori_arr)

Original array: [[6 5 7]
 [3 5 2]
 [2 6 8]]
compute the product all the elements of the array: 604800
Array to add: [ 8 15  4]
privious array: [[14 20 11]
 [11 20  6]
 [10 21 12]]
after adding the elements of the array: [[14 20 11]
 [11 20  6]
 [10 21 12]]


## 5. Sorting, Comparisons, and Boolean Logic


In [21]:
# Sorting
array = np.array([4, 2, 7, 1, 3])
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# Comparisons and masks
boolean_mask = array > 3
print("Elements greater than 3:", array[boolean_mask])


Sorted array: [1 2 3 4 7]
Elements greater than 3: [4 7]


**Exercise 5:**
- Sort an array of random integers between 10 and 50.
- Find all elements in a NumPy array that are less than a given threshold.


In [3]:
#your codes
array=np.random.randint(10,51,size=(3,3))
array.sort()
print("Sorted Array:\n", array)
threshold=30
boolean_mask=array<threshold
print("Elements less than threshold:", array[boolean_mask])

Sorted Array:
 [[11 20 26]
 [28 43 44]
 [23 34 36]]
Elements less than threshold: [11 20 26 28 23]
